name: My first Action
on: [pull_request]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print pull request success
        run: echo "pull request successful!"

  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print files
        run: ls -a







